// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../js/CanvasHandler.js', ['CanvasHandler'], ['Card']);
goog.addDependency('../../../../../js/CommunicationHandler.js', ['CommunicationHandler'], []);
goog.addDependency('../../../../../js/InteractiveGraphicEntity.js', ['InteractiveGraphicEntity'], ['JS']);
goog.addDependency('../../../../../js/Card.js', ['Card'], ['InteractiveGraphicEntity','JS']);
goog.addDependency('../../../../../js/Painter.js', ['Painter'], []);
goog.addDependency('../../../../../js/js.js', ['JS'], ['InteractiveGraphicEntity']);
